spring.application.name=SmartBankAI
server.port=8082

# PostgreSQL Render Veritabani Baglantisi
spring.datasource.url=jdbc:postgresql://dpg-dacu9u2ea03c73dfj30g-a.frankfurt-postgres.render.com:5432/smartbank_db_i3s1?sslmode=require
spring.datasource.username=smartbank_user
spring.datasource.password=g612QwEeikrEOj8YQkKAWNFyMnNXlidH
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Ayarlari (Tablolari Render Postgres uzerinde otomatik olusturur)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# data.sql kapali
spring.sql.init.mode=never

# FastAPI Bulut Baglantisi
ai.service.url=https://smartbank-ai-k1i9.onrender.com/analyze