spring.application.name=SmartBankAI
server.port=8081

# SQL Server Veritabani Baglantisi
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=SmartBankAI_DB;encrypt=false;trustServerCertificate=true
spring.datasource.username=smartbank_user
spring.datasource.password=SmartBank123!
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Hibernate Ayarlari
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# data.sql kapali
spring.sql.init.mode=never

# FastAPI Baglantisi
ai.service.url=http://localhost:8000/analyze